steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${_GCP_PROJECT_ID}/bradspicks:$COMMIT_SHA', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${_GCP_PROJECT_ID}/bradspicks:$COMMIT_SHA']
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - deploy
      - 'bradspicks-$COMMIT_SHA'
      - '--image'
      - 'gcr.io/${_GCP_PROJECT_ID}/bradspicks:$COMMIT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - '${_REGION}'
      - '--allow-unauthenticated'  # Public access

images:
  - 'gcr.io/${_GCP_PROJECT_ID}/bradspicks:$COMMIT_SHA'

timeout: '1200s'

substitutions:
  _GCP_PROJECT_ID: 'mindful-coder-450-821-f3'  # Set this manually or in GitHub Actions
  _REGION: 'us-central1'

