steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/bradspicks:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/bradspicks:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - deploy
      - 'bradspicks-$COMMIT_SHA'
      - '--image'
      - 'gcr.io/$PROJECT_ID/bradspicks:$COMMIT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - '$REGION' #This can be defined as a substitution variable
      - '--allow-unauthenticated' # Add this line if public access is needed

images:
  - 'gcr.io/$PROJECT_ID/bradspicks:$COMMIT_SHA'

timeout: '1200s'

substitutions:
  REGION: 'us-central1' # Example; can be set by cloud build trigger

