steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/bradspicks', '.']

  # Step 2: Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/bradspicks']

  # Step 3: Deploy the app to Cloud Run (you can adjust this for other deployment targets like GKE)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'bradspicks'  # Replace with your app name
      - '--image'
      - 'gcr.io/$PROJECT_ID/bradspicks'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'

# Optionally, you can define your images here (to make it easier to track)
images:
  - 'gcr.io/$PROJECT_ID/bradspicks'

timeout: '1200s'  # You can adjust the timeout as needed
