name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Authenticate Docker to Google Artifact Registry
        run: echo "${{ secrets.GCP_SEERVICE_ACCOUNT_KEY }}" | docker login -u _json_key --password-stdin https://us-central1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/bradspicks-repo/bradspicks:${{ github.sha }} .
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/bradspicks-repo/bradspicks:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: bradspicks
          image: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/bradspicks-repo/bradspicks:${{ github.sha }}
          region: us-central1
          project_id: ${{ secrets.GCP_PROJECT_ID }}
