name: CI/CD for BradsPicks

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

    - name: Configure Docker to Use gcloud CLI
      run: |
        gcloud auth configure-docker --quiet

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/bradspicks:${{ github.sha }}

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: bradspicks
        image: ghcr.io/${{ github.repository_owner }}/bradspicks:${{ github.sha }}
        region: us-central1
        project_id: ${{ secrets.GCP_PROJECT_ID }}  # Provide the GCP project ID here
