name: CI/CD for BradsPicks

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'  # Fix: Ensure it's set in GitHub Secrets

    - name: Configure Docker to Use gcloud CLI
      run: |
        gcloud auth configure-docker --quiet

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/bradspicks:${{ github.sha }}
   
    - name: Grant Artifact Registry Permissions
      run: |
       gcloud projects add-iam-policy-binding ${{ secrets.GCP_PROJECT_ID }} \
        --member="serviceAccount:${{ secrets.GCP_PROJECT_NUMBER }}@cloudbuild.gserviceaccount.com" \
        --role="roles/artifactregistry.writer"

       gcloud projects add-iam-policy-binding mindful-coder-450821-f3 \
       --member="serviceAccount:github-actions@mindful-coder-450821-f3.iam.gserviceaccount.com" \
       --role="roles/artifactregistry.writer"
     
        
    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: bradspicks
        image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/bradspicks:${{ github.sha }}
        region: us-central1
        allow_unauthenticated: true
