name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Trigger this workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Google Cloud authentication
        uses: google-github-actions/auth@v1  # Use the latest version
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}  # Correct secret for the service account key

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate Docker to Google Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/bradspicks:${{ github.sha }} .

      - name: Push Docker image to Google Artifact Registry
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/bradspicks:${{ github.sha }}

     - name: Push Docker image to Google Artifact Registry
       run: |
         set -x  # Enable debug mode for this step
         docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/bradspicks:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy bradspicks-${{ github.sha }} \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/bradspicks:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
