name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Runs on pushes to the main branch

jobs:
  deploy:
    name: Build & Deploy to Google Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set Up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Google Cloud
        run: gcloud auth configure-docker --quiet

      # Build & Push Stats API
      - name: Build and Push Stats API
        run: |
          gcloud builds submit --tag gcr.io/brads-picks/stats-api api/

      - name: Deploy Stats API to Cloud Run
        run: |
          gcloud run deploy stats-api \
            --image gcr.io/brads-picks/stats-api \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated

      # Build & Push Scraper API
      - name: Build and Push Scraper
        run: |
          gcloud builds submit --tag gcr.io/brads-picks/fanduel-scraper scraper/

      - name: Deploy Scraper to Cloud Run
        run: |
          gcloud run deploy fanduel-scraper \
            --image gcr.io/brads-picks/fanduel-scraper \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
