
name: CI/CD for BradsPicks

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Latest version

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3  # Latest version
      with:
        context: .
        push: true
        tags: gcr.io/$PROJECT_ID/bradspicks:$GITHUB_SHA

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v0  # Latest version
      with:
        project_id: $PROJECT_ID
        service: bradspicks
        image: gcr.io/$PROJECT_ID/bradspicks:$GITHUB_SHA
        region: us-central1
        allow_unauthenticated: true
