name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Google Cloud credentials using the service account key
      - name: Set up Google Cloud credentials
        uses: google-github-actions/setup-gcloud@v3
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}  # Store your project ID in GitHub Secrets
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}  # Store your GCP service account key in GitHub Secrets

      # Set up Docker and build the image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/bradspicks:${{ github.sha }} .
      
      # Push Docker image to Google Container Registry
      - name: Push Docker image to GCR
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/bradspicks:${{ github.sha }}

      # Deploy to Google Cloud Run
      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy bradspicks-${{ github.sha }} \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/bradspicks:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
